### ISSUE TITLE
Suggestion: memberActionWithRefresh

### ISSUE THREAD

**Issue by adamdonahue** [mike-north/ember-api-actions#110]
We introduced the following into our code base and thought we'd share it in case you'd be interested in incorporating into `ember-api-actions`:

``` javascript
function memberActionWithRefresh() {
  const options = [...arguments];
  return function() {
    const payload = [...arguments];
    return memberAction.apply(this, options).apply(this, payload).then(data => {
      this.store.push(this.store.normalize(this.constructor.modelName, data));
    });
  };
}
```

**Comment by sescobb27** [comment]
you can use this one too,
```js
.then((data) => {
  let serializer = this.store.serializerFor(this.constructor.modelName);
  serializer.pushPayload(this.store, data);
})
```
this also works with dasherized attributes and plural types in relationships (which are jsonapi compliant but ember does not recognize them) see http://emberjs.com/api/data/classes/DS.Store.html#method_push
