### ISSUE TITLE
Sideloaded data

### ISSUE THREAD

**Issue by elidupuis** [mike-north/ember-api-actions#14]
Firstly, very useful addon. Thanks!

I'm having some trouble with a `memberAction` that returns some sideloaded data. The payload returned from my API seems solid, but the extra data doesn't appear in my local Store. Have you used this addon with sideloaded data?

We're still using `RESTAdapter`; does that make any difference?

**Comment by artsyca** [comment]
If I understand correctly, the `memberAction` will just call the store's `ajax` method. It's up to you to send the params and deal with the payload. This is kind of the pattern I'm using:

```javascript
item.finalize().then((payload) => {
  item.rollbackAttributes();
  this.store.pushPayload(item.constructor.modelName, payload);
});
```

**Comment by elidupuis** [comment]
Thanks @artsyca. I realized I could just use `store.pushPayload` the other day and it works great :+1: 

Out of curiosity, what's the purpose of rolling back the model attributes?

**Comment by medokin** [comment]
@elidupuis In my case the rollback is useful to get rid of the `dirty` state when I edit a model outside of ember-data and push the changes back.
