### ISSUE TITLE
Response not being parsed by Ember Data

### ISSUE THREAD

**Issue by adambedford** [mike-north/ember-api-actions#194]
I think I'm seeing an issue where the server response isn't being parsed into an Ember Data model. Is this expected behavior?

Server response:

```
{  
   "data":{  
      "id":"377",
      "type":"job-applications",
      "links":{  
         "self":"http://localhost:3000/api/v1/job-applications/377"
      },
      "attributes":{  
         "job-title":"Product Manager",
         "status":"interested",
         "location":"San Francisco",
         "notes":null,
         "job-description":null,
         "url":"https://angel.co/earnest/jobs/76578-product-manager?src=rec"
      },
      "relationships":{  
         "company":{  
            "links":{  
               "self":"http://localhost:3000/api/v1/job-applications/377/relationships/company",
               "related":"http://localhost:3000/api/v1/job-applications/377/company"
            }
         }
      }
   }
}
```

This is available as a plain JS object in the result of the promise. I was expecting it to be parsed into an `Ember.DS` model.

Is there a good way to get the result into a model if it doesn't happen automatically?

**Comment by mupkoo** [comment]
You can use [DS.Store.pushPayload](https://emberjs.com/api/ember-data/2.14/classes/DS.Store/methods/pushPayload?anchor=pushPayload) for this. 

It might be a good idea to add this as an option - `pushToStore: true`
