### ISSUE TITLE
using typescript with ember-api-actions

### ISSUE THREAD

**Issue by AleksandrBorovkov** [mike-north/ember-api-actions#447]
Hello,

Is it possible to use TypeScript with ember-api-actions? 

For example I have model with api action

` allowDownload(): unknown {
    return memberAction({ path: 'allow_download', type: 'put' });
  }`

And invoke this like

`await conference.allowDownload({
        allow_download: state,
      });`

**Comment by catz** [comment]
I guess it could be following

type Payload = {
  model: {
      ....
  };
};

  allowDownload(payload: Payload): Promise<{ your_model_name: YourModelName }> {
    return memberAction({ path: 'allow_download', type: 'put' }).apply(this, [
      payload,
    ]);
  }
