### ISSUE TITLE
should note versions of ember-data this addon is compatible with

### ISSUE THREAD

**Issue by koryteg** [mike-north/ember-api-actions#6]
not complaining here, probably should have updated my version of ember-data anyway, but I was on ember-data 1.0.0-beta.15 and had to update to version 1.0.0-beta.18 before it started working.

might be good to have the travis ci check the ember data builds as well or mark up what is supported and what is not supported.

**Comment by truenorth** [comment]
thanks for the heads up

**Comment by mike-north** [comment]
Addressed via b1189fa7d9f599731abc6a59bb6c113a38fe5bf5
