### ISSUE TITLE
collectionAction is not a function

### ISSUE THREAD

**Issue by allthesignals** [mike-north/ember-api-actions#7]
`ember install ember-api-actions`

Model:
```
import DS from 'ember-data';
import { memberAction, collectionAction } from 'npm:ember-api-actions';

const { attr } = DS;

export default DS.Model.extend({
  description: attr('string'),
  name: attr('string'),
  geometry: attr(),
  profile: belongsTo('profile'),
  search: collectionAction({ path: 'search' })
});
```

`Error while processing route: places.index npm_ember_api_actions.collectionAction is not a function @http://localhost:4200/assets/neighborhood-drawing-tool.js:389:13`

I'm assuming this has to do with how the import is happening. How can I install this add-on in ember-cli?

**Comment by mike-north** [comment]
Looks like a typo in your import. remove the `npm:` and you should be good to go!
```js
import { memberAction, collectionAction } from 'ember-api-actions';

```

**Comment by allthesignals** [comment]
Ah. That's how I had to import npm modules before. It seems to work now. Thanks, @mike-north!
