### ISSUE TITLE
Params sent in a GET payload are in "quotes"

### ISSUE THREAD

**Issue by pauldoerwald** [mike-north/ember-api-actions#70]
If I declare a collectionAction as follows:

    ...
    byToken: collectionAction({
      path: 'by_token',
      type: 'post'
    })

and then call it in a route like this:

    model(params) {
      this.store.createRecord('user').byToken({token: params.token});
    }

everything works. But, if I change the collectionAction type to 'get', the params arrive surrounded by quotes in the params:

    GET /users/by_token?%22token=abcdefg%22

**Comment by mike-north** [comment]
Confirmed bug

**Comment by mike-north** [comment]
Fixed and released in `0.1.6`
