### ISSUE TITLE
Should collectionAction be on store?

### ISSUE THREAD

**Issue by richmolj** [mike-north/ember-api-actions#8]
First, big thanks for this excellent and much-needed add-on.

Currently you need to call a collection action on an instance:

```es6
this.store.createRecord('person').autocomplete({q: 'abc'})
```

Since collection actions don't pertain to a single resource, this reads a little odd to me. I think the 'ember data way' might be more like:

```es6
this.store.autocomplete('person', {q: 'abc'})
```

It's not really a problem, but I'd love to see this repo in ember-data itself one day, and matching that API maybe greases the wheels to provide a more conventional API.

**Comment by mike-north** [comment]
Agree with this change to the API. It collection actions should either be on the store, or on the Model its self (as opposed to an instance of the model).

Example:

```js
import Person from 'app/models/person';

...

Person.autocomplete({q: 'abc'});
```

**Comment by elidupuis** [comment]
Any movement on this? I've been thinking about this again lately. Would be great to have an update here.

**Comment by Turbo87** [comment]
I think the proper API for this would be something like: 
```js
this.store.modelFor('person').autocomplete({q: 'abc'})
```

**Comment by trobrock** [comment]
:+1: what is left to be done on this? More than willing to help out.

**Comment by Geokoumpa** [comment]
Perhaps it's me using it wrong, but for a collection route I also need to push server response into store as  for it to be an ember data record:

```
		this.get('store').createRecord('match').random().then( (match)=> {
			match = this.get('store').pushPayload('match', match)
			return match;
		});
```

Is this correct?

**Comment by denniscastro** [comment]
@Geokoumpa yes. You need to push the payload

Ember doesnt push itself when you use custom routes

**Comment by mike-north** [comment]
Closing this issue, as #9 seems to be stalled out

**Comment by allthesignals** [comment]
Ooof, @Geokoumpa's solution works, but since apparently `#pushPayload` doesn't return anything (for now)... are you using a canary build? I cannot get that method to actually return anything.

**Comment by brandonjmckay** [comment]
any movement on this?
